/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "name" {
  type        = string
  description = <<-EOT
     Friendly name for the member account.
  EOT
}

variable "email" {
  type        = string
  description = <<-EOT
     Email address for the member account.
  EOT
}

variable "close_on_deletion" {
  type        = bool
  description = <<-EOT
     Close the member account on deletion.
  EOT
  default     = false
}

variable "create_govcloud" {
  type        = bool
  description = <<-EOT
     Create the member account in the GovCloud region.
  EOT
  default     = false
}

variable "iam_user_access_to_billing" {
  type        = bool
  description = <<-EOT
     Allow the IAM user to access billing information for the member account.
  EOT
  default     = false
}

variable "parent_id" {
  type        = string
  description = <<-EOT
     The ID of the parent account.
  EOT
  default     = null
}

variable "role_name" {
  type        = string
  description = <<-EOT
    the name of an IAM role that Organizations automatically preconfigures in
    the new member account. This role trusts the root account, allowing users
    in the root account to assume the role, as permitted by the root account
    administrator. The role has administrator permissions in the new member
    account.
  EOT
  default     = null
}

variable "tags" {
  type        = map(string)
  description = <<-EOT
    A map of tags to assign to the member account.
  EOT
  default     = null
}

variable "prevent_destroy" {
  type        = bool
  description = <<-EOT
    Prevent the module from destroying the Account
  EOT
  default     = true
}
