/**
  * Examples should illustrate typical use cases.
  * For multiple examples each should have its own directory.
  *
  * > Running module examples uses a local state file.
  * > If you delete the .terraform directory the resources
  * > will be orphaned.
*/

/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "name" {}
variable "email" {}
variable "close_on_deletion" { default = true }
variable "create_govcloud" { default = false }
variable "iam_user_access_to_billing" { default = false }
variable "parent_id" { default = null }
variable "role_name" { default = null }
variable "tags" { default = null }
variable "prevent_destroy" { default = false }


module "this" {
  source                     = "../../"
  name                       = var.name
  email                      = var.email
  close_on_deletion          = var.close_on_deletion
  create_govcloud            = var.create_govcloud
  iam_user_access_to_billing = var.iam_user_access_to_billing
  parent_id                  = var.parent_id
  role_name                  = var.role_name
  tags                       = var.tags
  prevent_destroy            = var.prevent_destroy
}

output "result" {
  description = <<-EOT
    The result of the module.
  EOT
  value       = module.this.result
}
