/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "result" {
  description = <<-EOT
      The result of the module.
    EOT
  value       = aws_lambda_function.this
}

output "cluster" {
  value = data.aws_eks_cluster.this
}

output "invocation" {
  value = aws_lambda_invocation.this
}
