/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "cluster_name" {
  type        = string
  description = <<-EOT
      Name of the EKS cluster to configure.
    EOT
}
