/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "result" {
  description = <<-EOT
      The result of the module.
    EOT
  value = {
    aws_rds_global_cluster             = aws_rds_global_cluster.this
    aws_rds_cluster_primary            = aws_rds_cluster.primary
    aws_rds_cluster_secondary          = aws_rds_cluster.secondary
    aws_rds_cluster_instance_primary   = aws_rds_cluster_instance.primary
    aws_rds_cluster_instance_secondary = aws_rds_cluster_instance.secondary

  }
}
