/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
  */


variable "aws_service_access_principals" {
  type        = list(string)
  description = <<-EOT
    The AWS service principals to enable access to the bucket
  EOT
  default     = null
}

variable "enabled_policy_types" {
  type        = list(string)
  description = <<-EOT
    The policy types to enable for the bucket
  EOT
  default     = null
  validation {
    condition = var.enabled_policy_types == null || contains([
      "AISERVICES_OPT_OUT_POLICY",
      "BACKUP_POLICY",
      "SERVICE_CONTROL_POLICY",
      "TAG_POLICY"
    ], coalesce(var.enabled_policy_types, []))
    error_message = "Must be one of AISERVICES_OPT_OUT_POLICY, BACKUP_POLICY, SERVICE_CONTROL_POLICY, TAG_POLICY."
  }
}

variable "feature_set" {
  type        = string
  description = <<-EOT
    The feature set to use for the bucket
  EOT
  default     = "ALL"
  validation {
    condition = var.feature_set == null || contains([
      "ALL",
      "CONSOLIDATED_BILLING",
    ], coalesce(var.feature_set, ""))
    error_message = "Must be one of ALL, CONSOLIDATED_BILLING."
  }
}

variable "prevent_destroy" {
  type        = bool
  description = <<-EOT
    Prevent the module from destroying the Organization
  EOT
  default     = true
}
